
""" 
Module: 
3250.1 Compilateurs 
Auteur: 
WICKI Sélien 
Date: 26.01.2025 
"""

# Allowed arguments for each instruction
style_arguments = ["#name", "#font", "#fontSize", "#font_color"]
page_number_arguments = ["#pageNumberPosition", "#pageNumberFontSize", "#pageNumberFont", "#pageNumberFontColor", "#pageNumberStart"]
section_arguments = ["#style"]
title_arguments = ["#style", "#level"]
numberize_title_arguments = ["#numberizeTitleStart"]


# Default values for optional arguments
default_font = "Helvetica"
default_color = "black"
default_font_size = 12
default_page_number_position = "bottom-left"

default_section_style = {
    "#name": "defaulSectiontStyle",
    "#font": default_font,
    "#fontSize": 12,
    "#font_color": "black"
}

default_title_style = {
    "#name": "defaultTitleStyle",
    "#font": default_font,
    "#fontSize": 12,
    "#font_color": "black"
}

default_page_number = {
    "#pageNumberPosition": "bottom-left",  # Position must have default value
    "#pageNumberFont": default_font,
    "#pageNumberFontSize": 10,
    "#pageNumberFontColor": "black",
    "#pageNumberStart": 1,
}

default_title = {
    "#level": 1,  # Default level for title
    "#style": "defaultTitleStyle"
}

default_section = {
    '#style': '"defaultStyle"'
}

default_numberize_title = {
    "#numberizeTitleStart": 1
}

# Generated by ChatGPT to know which color is supported
allowed_page_nb_positions = ["bottom-left", "bottom-right", "top-left", "top-right"]

# Range for the arguments
font_size_range = (4, 100)
title_level_range = (1, 10)



# Nested instructions allowed inside a section
section_nested_instructions = ["$bold", "$italic", "$underlined"]

